version: 2.1
orbs:
  slack: circleci/slack@4.13.3

executors:
  executor:
    docker:
      - image: cimg/node:lts
        environment:
          NODE_PATH: usr/local/lib/node_modules
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: yarn install
  test:
    steps:
      - run:
          name: Execute unit test
          command: yarn test
  slack-notify:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
          mentions: "@shiro_pon"
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "@shiro_pon"

jobs:
  build:
    executor: executor
    steps:
      - checkout
      - install_deps
      - test
      - run:
          name: Build
          command: yarn build

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: SLACK_ACCESS_TOKEN
