version: 2.1
orbs:
  slack: circleci/slack@4.13.3

executors:
  executor:
    docker:
      - image: cimg/node:lts
    working_directory: /home/circleci/study-circleci

commands:
  slack-notify:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
          mentions: "@shiro_pon"
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "@shiro_pon"

jobs:
  setup:
    executor: executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install

      - persist_to_workspace:
          root: /home/circleci/study-circleci
          paths:
            - node_modules
  typecheck:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: TypeCheck
          command: yarn typecheck
  lint:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  jest:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Jest
          command: yarn jest
  build:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - slack-notify

workflows:
  version: 2
  workflow:
    jobs:
      - setup
      - typecheck:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - jest:
          requires:
            - setup
      - build:
          requires:
            - setup
          context: SLACK_ACCESS_TOKEN
